USE Examples 
GO
 SELECT * FROM RealSample 
 WHERE ROUND (R,2)=1

 --WHERE R BETWEEN 0.99 AND 1.01

 SELECT GETDATE ()
 SELECT GETUTCDATE ()

 SELECT SYSDATETIME ()
 SELECT SYSUTCDATETIME ()

 SELECT SYSDATETIMEOFFSET ()
 
 SELECT DATENAME (DAY , GETDATE())
 SELECT DATENAME (MONTH  , GETDATE())
 SELECT DATENAME (YEAR  , GETDATE())
 SELECT DATENAME (WEEKDAY  , GETDATE())


 SELECT DATEPART (WEEKDAY, GETDATE())
 SELECT DATEPART  (DAY , GETDATE())
 SELECT DATEPART  (WEEK  , GETDATE())

 SELECT EOMONTH (GETDATE())

 SELECT DATEDIFF (DAy,GETDATE(),'2025-10-15')
  SELECT DATEDIFF (MINUTE ,GETDATE(),'2025-10-15')
   SELECT DATEDIFF (SECOND ,GETDATE(),'2025-10-15')
   SELECT DATEDIFF (WEEK  ,GETDATE(),'2025-10-15')

   SELECT DATEADD (day,8,GETDATE ())
      SELECT DATEADD (day,-8,GETDATE ())

	  SELECT DATEADD (year,1,GETDATE ())
	   SELECT DATEADD (year,1.5,GETDATE ())


	   SELECT DATEDIFF (DAy,GETDATE(),'2025-10-15').........positive.
	    SELECT DATEDIFF (DAy,'2025-10-15',GETDATE()) ...........negative value day



		